<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Phalcon PHP Framework</title>
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico') ?>"/>
</head>
<body>
<div class="container">
    <h1>Please login and password</h1>
    <form id="login-form" action="" method="POST" onsubmit="sendLogin(event)">
        <p>Логин:</p>
        <input name="login" id="login" value=""/><br/>
        <p>Пароль:</p>
        <input name="password" id="password" value=""/><br/>
        <br/>
        <button id="btn-submit">Войти</button>
    </form>
    <script>
        var login = document.getElementById('login');
        var password = document.getElementById('password');
        var xhr = new XMLHttpRequest();

        function sendLogin(e) {
            e.preventDefault();
            var request = '{"jsonrpc": "2.0","method":"authorize","params":{ ' +
                '"login" : "' + login.value + '", ' +
                '"password":"' + password.value + '"},"id":1}';
            xhr.open('POST', '/api');
            xhr.setRequestHeader("Content-Type", "application/json");

            xhr.onload = function () {
                if (xhr.status != 200) { // analyze HTTP status of the response
                    console.log('Error' + xhr.status + ':' + xhr.response); // e.g. 404: Not Found
                } else { // show the result
                    //var data = xhr.response;
                    var data = JSON.parse(xhr.response);
                    console.log(data);
                    if (data.error == false) {
                        alert(data.result);
                    } else {
                        alert(data.result);
                    }
                }
            };

            xhr.onerror = function () {
                alert("неверный логин или пароль");
            };

            xhr.send(request);
            return false;
        }
    </script>
</div>
</body>
</html>
